openapi: 3.0.0
info:
  title: JWT Authentication for ChatKit Endpoint
  version: 1.0.0
  description: API contract for JWT token validation and user identification on the /support/chatkit endpoint.

servers:
  - url: /

paths:
  /support/chatkit:
    post:
      summary: Authenticate user and process ChatKit message
      description: Validates JWT token, identifies user, and proceeds with ChatKit message processing.
      operationId: processChatKitMessage
      requestBody:
        description: ChatKit message payload
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The message from the user to the ChatKit service.
              required:
                - message
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User successfully authenticated and ChatKit processing initiated.
          content:
            text/event-stream:
              schema:
                type: string
                example: "[Normal ChatKit response continues...]"
        '401':
          description: Unauthorized - Invalid or expired JWT token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid or expired JWT token"
                  status:
                    type: integer
                    example: 401
        '404':
          description: Not Found - User not found or no active sessions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not found with provided email"
                  status:
                    type: integer
                    example: 404
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
